description: "BLUG - Bergen Linux (and BSD) User Group"
org_name: "Bergen Linux User Group"

locale:
  date_format: "2006-01-02"
  time_format: "15:04"

site_footer:
  copyright: "&copy; {year} BLUG"
